name: sigmail_client
description: "A new Flutter project."
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # Dependency Injection
  get_it: ^7.6.7
  # Routing
  go_router: ^14.2.0
  # HTTP Client
  dio: ^5.4.1
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  # Value equality
  # equatable: ^2.0.5 # Already listed above
  # Functional programming
  dartz: ^0.10.1
  # Logging
  logger: ^2.5.0
  # Path provider (для работы с путями файлов/директорий)
  path_provider: ^2.1.2
  # File Picker (для выбора файлов, например, вложений)
  file_picker: ^10.1.9
  # Image Picker (для выбора изображений из галереи/камеры)
  image_picker: ^1.0.7
  # UUID generation
  uuid: ^4.3.3
  # MinIO Client
  minio: ^3.5.7
  # SignalR Client
  signalr_core: ^1.1.1
  # Collection (для firstWhereOrNull и других утилит)
  collection: ^1.18.0
  # Freezed & Json Annotation (для моделей данных)
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  # HTTP Client
  http: ^1.1.0
  # Для открытия файлов после скачивания вложений
  open_file: ^3.3.2
  # SharedPreferences (для локального хранения)
  shared_preferences: ^2.2.2
  # RxDart (для debounceTime и других Rx операторов)
  rxdart: ^0.27.7
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  url_launcher: ^6.3.1
  path: ^1.9.0
  mime: ^1.0.5
  scroll_to_index: ^3.0.1
  emoji_picker_flutter: ^4.3.0
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.14.3

  # Firebase & Push Notifications - УДАЛЕНО
  # firebase_core: ^3.1.1 
  # firebase_messaging: ^15.0.1 
  # flutter_local_notifications: ^17.2.1 
  

dependency_overrides:
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  # Code generation
  build_runner: ^2.4.8 
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/app_icon.png
    # - assets/icons/
    # - assets/ca/
    - .env
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
